default: &default
  adapter: postgresql
  user: todo
  password: todo
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: todo_development

test:
  <<: *default
  database: todo_test
