development:
  adapter: postgresql
  user: todo
  password: todo
  encoding: unicode
  database: todo_development
  host: localhost
  pool: 5

production:
  adapter: postgresql
  host: postgresql0.locum.ru
  database: q3pp_todo90
  user: q3pp_todo90
  password: YGl3kNYtCyW
  encoding: unicode
  pool: 5
